### ISSUE TITLE
Sellers can create auctions, and set features (description, category, starting price, reserve price, end date)

### ISSUE THREAD

**Issue by tt01924** [tt01924/WheelDeal#51]

**Comment by timfarkas** [comment]
I think @j-simpson1 is working on this right now

**Comment by timfarkas** [comment]
@j-simpson1 is this all done? feel free to close issue and move to done then

**Comment by j-simpson1** [comment]
Yes core functionality is done. Planning to implement file upload for images asap :)

**Comment by j-simpson1** [comment]
Perfect - sounds good!
