### ISSUE TITLE
BUG: Registration fails with 'Data too long for column password'

### ISSUE THREAD

**Issue by timfarkas** [tt01924/WheelDeal#63]
<img width="971" alt="image" src="https://github.com/user-attachments/assets/82aad5e5-51e3-4e9f-9361-618d62e78317">

I am getting "Database Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'password' at row 1" when entering passwords of any size

**Comment by timfarkas** [comment]
Maybe this is as a result of changing the password hashing algorithm? @PeaceES did it still work for you after changing?
also, it seems like the hashes still differ, maybe php also salts the hash by default?

**Comment by PeaceES** [comment]
It should be working now. I created a new pull request, lmk : )
